spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

jdbc:
  driverClassName : com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/jwt
  user: root
  pass: 1111

security:
   oauth2:
      resource:
         filter-order: 3